version: '3'
services:

  fdp:
    image: crs4/fairdatapoint:latest
    ports:
      - 80
    volumes:
      - ./application.yml:/fdp/application.yml:ro

  fdp-client:
    image: crs4/fairdatapoint-client:latest
    ports:
      - 8050:80
    environment:
      - FDP_HOST=fdp

  mongo:
    image: mongo:4.0.12
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

  blazegraph:
    image: metaphacts/blazegraph-basic:2.2.0-20160908.003514-6
    ports:
      - 9090:8080
    volumes:
      - blazegraph-data:/blazegraph-data

volumes:
  mongo-data:
  blazegraph-data:
